name: Check Azure Status

on:
  check_suite:
    types:
      - completed

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -sSL \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json; application/vnd.github.antiope-preview+json" \
          -X POST \
          -d '{"status":["in_progress"]}' \
          "${{ github.event.check_suite.url }}"
